project_id = "zmsuqdwleyqpdthaqvbi"

[functions.extract-medication]
verify_jwt = false

[functions.extract-exam]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
